"""Cria tabela de inscrições em cursos

Revision ID: 15872b6b8d07
Revises: 2ae278168ac4
Create Date: 2025-10-05 15:09:18.066366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15872b6b8d07'
down_revision = '2ae278168ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    # ### end Alembic commands ###
