"""Adiciona mensagem ao pedido de amizade

Revision ID: 277dddb333f6
Revises: 3d7359309bb5
Create Date: 2025-10-06 21:45:02.764610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277dddb333f6'
down_revision = '3d7359309bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_private_messages_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_column('message')

    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_private_messages_timestamp'))

    op.drop_table('private_messages')
    # ### end Alembic commands ###
