"""Adiciona campo last_seen ao User

Revision ID: 6693e3ab8bcb
Revises: 4843754f2f13
Create Date: 2025-09-29 20:12:31.988019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6693e3ab8bcb'
down_revision = '4843754f2f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
