"""Cria tabela de avaliações de cursos

Revision ID: 68793acb978d
Revises: 15872b6b8d07
Create Date: 2025-10-05 15:22:43.128866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68793acb978d'
down_revision = '15872b6b8d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_ratings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_ratings')
    # ### end Alembic commands ###
