"""Adiciona campo 'confirmed' ao User

Revision ID: 82f2b3f44129
Revises: 4843754f2f13
Create Date: 2025-10-05 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f2b3f44129'
# O 'down_revision' pode variar dependendo do seu último arquivo de migração.
# Verifique o nome do arquivo anterior no seu diretório de 'versions' se necessário.
down_revision = '4843754f2f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Adicionamos 'server_default='f'' para que o PostgreSQL saiba
        # qual valor padrão usar para as linhas que já existem.
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=False, server_default='f'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')
    # ### end Alembic commands ###