"""Adiciona campos de perfil e pontuação ao User

Revision ID: 90765cd91855
Revises: 50d54098bc14
Create Date: 2025-09-18 19:45:17.096120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90765cd91855'
down_revision = '50d54098bc14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), server_default='default.jpg', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('bio')
        batch_op.drop_column('score')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
